### ISSUE TITLE
六进 todo-list

### ISSUE THREAD

**Issue by arlmy** [arlmy/arlmy.github.io#2]
[作业要求](https://github.com/cp4/AVoyage2HTML5/issues/6)
- [x] “关于”页面文案：https://www.douban.com/doulist/11392914/
- [x] 设计稿：https://modao.cc/app/76ce98dcd22c2d81416c11eaa0b697757448febd
- [x] HTML 骨架
- [x] CSS 选择器复盘
- [x] 达成设计效果
- [x] 页面优化

**Comment by cp4** [comment]
赞呐，我觉得提交到公共仓库似乎更合适，如果你感到在博客仓不很贴切的话
